language: java
install: true

jdk:
  - openjdk8
  - openjdk9
  - openjdk11

env:
  global:
    - CI=true
    - AWS_ACCESS_KEY_ID=fakeval
    - AWS_SECRET_ACCESS_KEY=fakeval
    - AWS_DEFAULT_REGION=eu-west-1

script:
  - ./gradlew clean build check

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

#before_install:
#  - python --version
#  - pip --version
#  - sudo pip install --upgrade awscli
#  - aws --version
#  - sudo pip install --upgrade aws-sam-cli
#  - sam --version

#jobs:
#  include:
#    - stage: Run tests
#      script:
#        - ./gradlew assemble --info
